language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t anirudhan/docker-react -f Dockerfile2.dev .
script:
  - docker run -e CI=true anirudhan/docker-react npm run test
